"""Native paired-seed gates: tails, generic N, nonunit base and known factors.

Small inputs are valid lcm Stage1 points generated by the independent Python
reference. Large known-factor saves retain their existing CPU provenance.
"""
import argparse
import hashlib
import importlib.util
import json
import math
import os
from pathlib import Path
import re
import subprocess
import sys

root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(root / 'tools/bench'))
from bench_stage2_budget_scaling import fields


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--exe', type=Path, required=True)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--factor-evidence', type=Path, required=True)
    a = p.parse_args()
    out = a.output.resolve()
    out.mkdir(parents=True, exist_ok=True)
    if any(out.iterdir()):
        p.error('Use a fresh output directory')
    exe = a.exe.resolve()
    snapshot = exe.parent / 'frozen_sources_manifest.json'
    frozen = json.loads(snapshot.read_text(encoding='utf-8-sig'))
    identity = dict(binary_sha256=sha(exe), snapshot_sha256=sha(snapshot), tool_sha256=sha(__file__),
                    factor_evidence_sha256=sha(a.factor_evidence))

    def verify():
        if sha(exe) != identity['binary_sha256'] or frozen['binary_sha256'] != sha(exe) or sha(snapshot) != identity['snapshot_sha256']:
            raise ValueError('Binary/source identity changed')
        for name, h in frozen['sources'].items():
            if sha(exe.parent / 'sources' / name) != h:
                raise ValueError('Frozen dependency changed')
        if sha(__file__) != identity['tool_sha256'] or sha(a.factor_evidence) != identity['factor_evidence_sha256']:
            raise ValueError('Gate/provenance changed')

    spec = importlib.util.spec_from_file_location('suyama_ref', root / 'tools/stat/suyama_mont_ref.py')
    ref = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ref)
    cases = []
    for bits in (127, 521, 1279):
        n = (1 << bits) - 1
        r = ref.stage1(26, 20, n)
        if r['gcd'] != 1:
            raise ValueError('Reference Stage1 failed')
        for count in (2, 65, 66):
            cases.append(dict(name=f'm{bits}_i{count}', N=n, X=r['x'], sigma=26, B1=20,
                              B2=210 * (count - 2) if count > 2 else 21, D=210, block=8, cpu_stage1=True))
    n = (1 << 128) + 1
    r = ref.stage1(26, 20, n)
    cases.append(dict(name='generic129', N=n, X=r['x'], sigma=26, B1=20, B2=13230, D=210, block=64, cpu_stage1=True))
    n = 103 * 65537
    r = ref.stage1(26, 2, n)
    hx, hz = ref.ladder(210, r['x'], 1, r['a24'], n)
    if r['gcd'] != 1 or math.gcd(hz, n) != 103:
        raise ValueError('Nonunit base fixture changed')
    cases.append(dict(name='nonunit_base', N=n, X=r['x'], sigma=26, B1=2, B2=13230, D=210, block=8,
                      cpu_stage1=True, expected_base_nonunit=True, expected_factor=103))
    for case in cases:
        saved = out / (case['name'] + '.save')
        x, n, b1, sigma = case['X'], case['N'], case['B1'], case['sigma']
        saved.write_text(f'METHOD=ECM; SIGMA={sigma}; B1={b1}; N={n}; X=0x{x:x}; CHECKSUM={b1*sigma*n*x%4294967291};\n', encoding='utf-8')
        case.update(save=str(saved), save_sha256=sha(saved))
    evidence = json.loads(a.factor_evidence.read_text(encoding='utf-8'))
    for old in evidence['cases'][:2]:
        if not old['cpu_reference_verified'] or sha(old['save']) != old['save_sha256']:
            raise ValueError('Known-factor save/provenance changed')
        record = next(row['result'] for row in evidence['runs'] if row['index'] == old['index'])
        cases.append(dict(name='factor_' + str(old['index']), save=old['save'], save_sha256=old['save_sha256'],
            N=int(record['N_hex'], 16), sigma=record['sigma'], B1=record['B1'], B2=record['B2'], D=record['requested_D'],
            block=8, known_factors=old['expected_factors'], cpu_stage1=True))
    data = dict(identity=identity, reference_sha256=sha(root / 'tools/stat/suyama_mont_ref.py'), cases=cases, runs=[])
    dest = out / 'summary.json'

    def persist():
        dest.write_text(json.dumps(data, indent=2), encoding='utf-8')

    ini = out / 'manual.ini'
    ini.write_text('[gpu]\ndevice=1\n', encoding='utf-8')
    env = {k: v for k, v in os.environ.items() if not k.startswith('NTT_')}
    env.update(NTT_NO_PROGRESS='1', NTT_D_MODEL='0', NTT_GIANT_CHAIN_MIN='0',
        NTT_GIANT_SEED_CHECK='1', NTT_GFINV_SEG_CHECK='1', NTT_FOLD_DEVICE_MAX_MB='0',
        NTT_POINT_MERSENNE='1', CUDA_LAUNCH_BLOCKING='0')
    persist()
    for case in cases:
        results = []
        for mode in (0, 1):
            verify()
            if sha(case['save']) != case['save_sha256']:
                raise ValueError('Input save changed')
            name = case['name'] + '_' + str(mode)
            log, result = out / (name + '.log'), out / (name + '.jsonl')
            cmd = [str(exe), '--ini', str(ini), '--save', case['save'], '--b2', str(case['B2']), '--d', str(case['D']),
                '--device', '1', '--factor-only', '--log', str(log), '--results', str(result)]
            unit = 'known_factors' not in case and not case.get('expected_base_nonunit')
            proc = subprocess.run(cmd, env=env | dict(NTT_GIANT_SEED_PAIR=str(mode),
                NTT_GIANT_CHAIN_BLOCK=str(case['block']), NTT_GIANT_CHAIN_CHECK='1' if unit else '0'),
                capture_output=True, timeout=300)
            (out / (name + '_driver.log')).write_bytes(proc.stdout + proc.stderr)
            if proc.returncode:
                raise ValueError('Actual curve failed: ' + name)
            r = json.loads(result.read_text(encoding='utf-8').splitlines()[-1])
            text = log.read_text(encoding='utf-8')
            if (r['bad_factors'] or r['B1'] != case['B1'] or r['B2'] != case['B2'] or r['sigma'] != case['sigma'] or
                    int(r['N_hex'], 16) != case['N'] or
                    any(not 1 < int(f) < case['N'] or case['N'] % int(f) for f in r['factors'])):
                raise ValueError('Input/factor validation failed: ' + name)
            if not all(token in text for token in ('gmp_selftest_bad=0', 'gmp_check_bad=0', 'pending=0')):
                raise ValueError('Missing arithmetic checks')
            seed, pair = fields(text, 'real_giant_seed'), fields(text, 'real_giant_seed_pair')
            if int(seed['chunks']) == 0:
                raise ValueError('Fixture bypassed actual seed path')
            if mode and case.get('expected_base_nonunit'):
                if pair['base_nonunits'] != '1' or pair['chunks'] != '0' or pair['base_builds'] != '1':
                    raise ValueError('Actual nonunit did not fall back')
            elif mode and unit and int(pair['chunks']) == 0:
                raise ValueError('Paired path unused')
            if unit:
                affine = [dict(re.findall(r'(\w+)=([^\s]+)', row)) for row in re.findall(r'giant_chain_check: (.*)', text)]
                if len(affine) != int(seed['chunks']) or any(int(row['mismatches']) for row in affine):
                    raise ValueError('Full affine comparison failed')
            if int(seed['checked_words']) != 2 * ((case['N'].bit_length()+63)//64) * int(seed['points']):
                raise ValueError('Seed comparison coverage incomplete')
            if seed['segments'] != seed['segment_checks']:
                raise ValueError('Segment comparison coverage incomplete')
            for factor in case.get('known_factors', []) + ([str(case['expected_factor'])] if 'expected_factor' in case else []):
                if not any(int(f) % int(factor) == 0 for f in r['factors']):
                    raise ValueError('Known factor no longer covered: ' + factor)
            row = dict(name=name, mode=mode, command=cmd, result=r, seed=seed, pair=pair, log=str(log), log_sha256=sha(log))
            data['runs'].append(row)
            results.append(r['factors'])
            verify()
            persist()
            print(name, 'passed', 'paired_chunks=' + pair['chunks'], 'nonunit=' + pair['base_nonunits'], flush=True)
        case['same_raw_factor_set'] = set(results[0]) == set(results[1])
        # Projective representatives can split composite gcds differently. For
        # the nonunit fallback, however, the entire original path must be identical.
        if case.get('expected_base_nonunit') and not case['same_raw_factor_set']:
            raise ValueError('Nonunit fallback changed original raw factors')
    data.update(complete=True, passed=len(data['runs']), failed=0,
                scope='Real lcm Stage1 saves; same-binary seed/segment/affine comparisons, actual nonunit fallback and known proper factors. Not general 16384-bit acceptance.')
    persist()


if __name__ == '__main__':
    main()
